queryParameters:
  limit?:
    displayName: Limit
    type: number
    description: Amount of objects retrieved in the response
    example: 10
  offset?:
    displayName: Offset
    type: number
    description: The offset specifies the offset of the first row to return
    example: 1
  sort?:
    displayName: Sort
    type: string
    description: Property to sort by
    example: 'name'
  ascending?:
    displayName: Ascending
    type: boolean
    description: Order for sorting
    example: true
