#%RAML 1.0 Trait

queryParameters:
  sort:
    required: false
    description: The field to sort on.
    type: string
    enum: [<<field_1>>, <<field_2>>]
    default: <<default>>
  ascending:
    description: Whether to sort ascending or descending
    type: boolean
    default: true
