#%RAML 1.0 ResourceType

usage: Use this resourceType to represent an organization category
description: Category
patch:
  displayName: Updates category config
  description: |
    Updates a category configuration
    - Body should be application/json. This is not specified in the raml as it conflicts with Osprey.
  is: [updateableByForce]
  body:
    "*/*":
      example: !include ../examples/v2/patchCategoryTagConfigurationBody.json
  responses:
    200:
      body:
        application/json:
          type: !include ../schemas/category-configuration.json
          example: !include ../examples/category-configuration.json
delete:
  description: Deletes a category configuration
  is: [deleteableByForce]
  responses:
    204:
