#%RAML 1.0 ResourceType
description: Portal resource
usage: Use this resourceType to get a portal resource

get:
  description: Gets portals resource
  responses:
    200:
      description: Retrieved file as a binary content
