#%RAML 1.0 ResourceType

usage: Use this resourceType to represent saved search queries
description: Saved search queries
get:
    description: Gets a list of queries
    is: [ pagination ]
    responses:
        200:
            body:
                application/json:
                    type: !include ../schemas/search-queries.json
                    example: !include ../examples/search-queries.json
post:
    description: Creates a new query
    body:
        application/json:
            type: !include ../schemas/create-search-query.json
            example: !include ../examples/search-query.json
    responses:
        201:
            body:
                application/json:
                    example: !include ../examples/search-query.json
