#%RAML 1.0 ResourceType

usage: Use this resourceType to represent a collection of asset reviews
description: A collection of asset reviews
get:
    description: Gets a list of reviews
    queryParameters:
        includeComments:
            displayName: IncludeComments
            type: boolean
            description: Indicates to include comments or not in reviews
            example: false
            required: false
    responses:
        200:
            body:
                application/json:
                    type: !include ../schemas/reviews.json
                    example: !include ../examples/reviews.json
post:
    description: Creates a new asset review
    body:
        application/json:
            type:  !include ../schemas/post-review-body.json
            example: !include ../examples/post-review-body.json
    responses:
        201:
            body:
                application/json:
                    type: !include ../schemas/review.json
                    example: !include ../examples/review.json
